kind: pipeline
type: docker
name: docker-runner

platform:
  os: linux
  arch: amd64

steps:
  - name: unit-tests
    image: golang:1.14
    volumes:
    - name: deps
      path: /go
    commands:
      - bash ./scripts/install_consul.sh
      - bash ./scripts/unit_test.sh

trigger:
  event:
    - push

---
kind: pipeline
type: exec
name: exec-runner

platform:
  os: linux
  arch: amd64

steps:
  - name: integration-tests
    environment:
      COMPOSE_INTERACTIVE_NO_CLI: 1
    commands:
      - make build
      - bash ./scripts/test.sh test all
      - make clean

trigger:
  event:
    - push
