kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.14
    volumes:
    - name: deps
      path: /go
    commands:
      - bash ./scripts/unit_test.sh

trigger:
  event:
    - push
