// Code generated by "stringer -type JobStatus"; DO NOT EDIT

package jobs

import "fmt"

const jobStatusname = "statusUnknownstatusHealthystatusUnhealthystatusMaintenance"

var jobStatusindex = [...]uint8{0, 13, 26, 41, 58}

func (i JobStatus) String() string {
	if i < 0 || i >= JobStatus(len(jobStatusindex)-1) {
		return fmt.Sprintf("JobStatus(%d)", i)
	}
	return jobStatusname[jobStatusindex[i]:jobStatusindex[i+1]]
}
