// Code generated by "stringer -type EventCode"; DO NOT EDIT

package events

import "fmt"

const _EventCode_name = "ExitSuccessExitFailedStatusHealthyStatusUnhealthyStatusChangedTimerExpiredQuitStartupShutdown"

var _EventCode_index = [...]uint8{0, 11, 21, 34, 49, 62, 74, 78, 85, 93}

func (i EventCode) String() string {
	if i < 0 || i >= EventCode(len(_EventCode_index)-1) {
		return fmt.Sprintf("EventCode(%d)", i)
	}
	return _EventCode_name[_EventCode_index[i]:_EventCode_index[i+1]]
}
